name: Release GeyserHacks
# workflow by TBYT, added nms reflectiosn from previous workflow file.
on: push

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Prepare NMS 1.17 mappings
        run: mvn ca.bkaw:paper-nms-maven-plugin:1.2:init -pl :nms-1_17_R1

      - name: Prepare NMS 1.18 mappings
        run: mvn ca.bkaw:paper-nms-maven-plugin:1.2:init -pl :nms-1_18_R1

      - name: Prepare NMS 1.18.2 mappings
        run: mvn ca.bkaw:paper-nms-maven-plugin:1.2:init -pl :nms-1_18_R2

      - name: Prepare NMS 1.19 mappings
        run: mvn ca.bkaw:paper-nms-maven-plugin:1.2:init -pl :nms-1_19_R1

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package -T 2C

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: spigot/target/GeyserHacks.jar
          allowUpdates: true
          bodyFile: "README.md"
          draft: false
          prerelease: false
          tag: "release"
          token: ${{ secrets.GITHUB_TOKEN }}

#    - name: Release
#       uses: softprops/action-gh-release@v1
#       if: startsWith(github.ref, 'refs/tags/')
#       with:
#         files: spigot/target/GeyserHacks.jar
